### ISSUE TITLE
error: Error: ENOENT, open 'out/data.json'

### ISSUE THREAD

**Issue by ady-giftly** [yui/yuidoc#114]
What are we doing wrong here??

bash-3.2$ yuidoc .
info: (yuidoc): Starting YUIDoc@0.3.35 using YUI@3.8.0pr2 with NodeJS@0.8.14
info: (yuidoc): Scanning for yuidoc.json file.
info: (yuidoc): Starting YUIDoc with the following options:
info: (yuidoc): { port: 3000, nocode: false, paths: [ '.' ], outdir: './out' }
info: (yuidoc): YUIDoc Starting from: .
warn: (docparser): unknown tag: controller, js/giftOptions.js:1
warn: (docparser): unknown tag: controller, js/giftOptions.js:161
warn: (docparser): Missing item type:  js/giftOptions.js:1
warn: (docparser): 
        Gift Options Controller:
Fetches via $http gift items by category and populates 
the gift select menu and options list
warn: (docparser): Missing item type:  js/giftOptions.js:59
warn: (docparser): Missing item type:  js/giftOptions.js:161
warn: (docparser): 
        Gift Box Controller:
populates data for the current selected or saved gift
info: (yuidoc): Making out dir: ./out
warn: (yuidoc): Outdir creation failed
info: (yuidoc): Parsed 1 files in 0.008 seconds
info: (builder): Building..
info: (builder): Compiling Templates
info: (builder): Making default directories: classes,modules,files
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: Error: ENOENT, open 'out/data.json'
error: --------------------------------------------------------------------------
error: Node.js version: v0.8.14
error: YUI version: 3.8.0pr2
error: YUIDoc version: 0.3.35
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------

**Comment by Robdel12** [comment]
What was the permissions fix?
