### ISSUE TITLE
404 after toggling sidebar

### ISSUE THREAD

**Issue by mattflaschen** [yui/yuidoc#127]
With yuidoc 0.3.36, no config file, and just:

`yuidoc .`

on index.html, if I click Modules, then back to Classes, then one of the class names, I get a 404.  Two components of the path are dropped.

When I first load index.html it is:

file:///home/user/some/multiple/component/path/modules/out/classes/ValidationError.html

When I toggle back and forth it is:

file:///home/user/some/multiple/component/path/classes/ValidationError.html

Two sub-directories are dropped, causing a 404.  Also (not as important), the order of the classes switches.

**Comment by okuryu** [comment]
@mattflaschen @VarunJoshi Is this still a problem for you? I need a reproducible example.

**Comment by okuryu** [comment]
Closing, please let me know if you still have any problems.
