### ISSUE TITLE
Support for multiple inheritance?

### ISSUE THREAD

**Issue by ghost** [yui/yuidoc#151]
Is there a way of listing multiple @extends tags in to a class block?  My framework utilizes multiple inheritance/mix-ins, and I've noticed such techniques have been on the rise in the community in the past several months.  This feature would be much appreciated!

**Comment by hayesmaker** [comment]
What if Widget extends DisplayComponent, can we not tell the user that Panel is a Widget and a DisplayComponent?

**Comment by okuryu** [comment]
Currently, you're not able do it with default theme, but I believe that you can do it by customizing theme. Did you mean that you want to hide private classes? if so, there is an issue #189 already.
