### ISSUE TITLE
Layout of default theme is broken

### ISSUE THREAD

**Issue by aquillano** [yui/yuidoc#159]
Looks like YUI grids css for the sidebar (25%) and main content (75%) aren't working correctly. Happy to provide more info if necessary.

![yuidoc-broken-layout](https://f.cloud.github.com/assets/206505/515567/456337ca-be7b-11e2-8959-86fe5465e39d.jpg)

**Comment by okuryu** [comment]
Closing, please let me know if you still have this issue.
