### ISSUE TITLE
Incorrect links generated in server "Item not found" page

### ISSUE THREAD

**Issue by sseemayer** [yui/yuidoc#161]
When using the YUIDoc CLI with the `--server` option, there is a custom error page displayed when an item cannot be found by the given URL (e.g. [http://localhost:3000/classes/wdwdwd](http://localhost:3000/classes/wdwdwd), assuming that `wdwdwd` is not a valid class). The error page shows the items that _are_ available, but the link `href` seems to be generated incorrectly, e.g.:

    <a href="..//classes/Molecule.html">Molecule</a>

Clicking this link brings me to e.g. [http://localhost:3000//classes/Molecule.html](http://localhost:3000//classes/Molecule.html), which still displays, but navigating to another class will give me a spinner icon that keeps on spinning because the following exception is thrown:

    Uncaught Error: SecurityError: DOM Exception 18 combo:4
        e.extend._storeState combo:4
        e.mix._defChangeFn combo:2
        o.fireComplex combo:6
        e.CustomEvent.fire combo:4
        E.fire combo:5
        e.mix._fireEvents combo:2
        e.mix._resolveChanges combo:2
        e.mix._change combo:2
        e.mix.add combo:2
        e.Router.e.extend._save combo:10
        n._html5.n._dispatching combo:10

I believe https://github.com/yui/yuidoc/blob/master/lib/server.js#L95 is the culprit. If I'm not mistaken, it should be enough to replace '../' with '..' - at least I can't think of situations where this might cause trouble?

I'm using the following versions:

Node.js version: v0.10.9
YUI version: 3.9.1
YUIDoc version: 0.3.44
Chromium version: 27.0.1453.93 (200836)

Best,
Stefan

**Comment by okuryu** [comment]
I cannot reproduce your problem. Please try the latest version and let me know if you still have the same issue.
