### ISSUE TITLE
YUIDoc Tab Change Issue

### ISSUE THREAD

**Issue by VarunJoshi** [yui/yuidoc#177]
I am having an issue with tab click on the generated documentation. When I click on the second tab and then on any sub links under that tab, the highlighted tab automatically changes to the first tab. Is this an issue? What am I doing wrong?

**Comment by okuryu** [comment]
Is this still a problem for you? Could you try the latest version v0.5.0?

**Comment by okuryu** [comment]
Closing, please let me know if you still have a same issue.
