### ISSUE TITLE
@ Not escapable in example

### ISSUE THREAD

**Issue by andrewnicols** [yui/yuidoc#179]
I was trying to include some example CSS with a media query in a module the other day, and the @ at the beginning of the media query caused the subsequent section to be entirely omitted. I tried escaping the @ in a variety of ways to no avail.

Example docblock which replicates the issue

```
    /**
     * Some function
     *
     * JS:
     *
     *     YUI().use('example-module', function(Y) {
     *     });
     *
     *
     * and the CSS:
     *
     *     div.foo {
     *         width: 100%;
     *     }
     *
     *     @media screen and (max-width: 767px) {
     *         div.foo {
     *             width: 100px;
     *         }
     *    }
     * @method someMethod
     */
```

**Comment by okuryu** [comment]
Fixed in v0.6.0.
