### ISSUE TITLE
'simple' theme breaks links to source files

### ISSUE THREAD

**Issue by ghost** [yui/yuidoc#186]
When using the **simple** theme, if I'm browsing the generated documentation and click in a source file,example:

    generated in myAPI.js:42

When I click *myAPI.js*, instead of taking me to:

    C:/Users/Me/Lib/JS/myProject/out/files/myAPI.js

It takes me to

    C:/Users/Me/Lib/JS/myProject/files/myAPI.js

Which obviously does not exist

**Comment by okuryu** [comment]
Reopen, this issue seems not to be a duplication of #187. I'll take a look for this.

**Comment by okuryu** [comment]
#309 is ready for review.
