### ISSUE TITLE
YuiDoc Not generating any class Doc

### ISSUE THREAD

**Issue by tvrhossain** [yui/yuidoc#205]
Hello, I m new to yuidoc.I used yuidoc.json for the config, it runs well but after I open the index.html, nothing is documented.I just want to know if javascript namespacing is documented in yuidoc.I have java-script file content that has namespacing type notation. I also tried to generate ONLY php doc by "yuidoc -e .php" command, which again is not documenting anything.

**Comment by okuryu** [comment]
Closing, please let me know if you have still any problems.
