### ISSUE TITLE
specifying Array type for parameters, return types - previously issue 198

### ISSUE THREAD

**Issue by rick-kilgore** [yui/yuidoc#229]
Previously issue 198, "Add ability to specify type of Array member", the proposed solution doesn't work for current yuidoc.

The original issue is here: https://github.com/yui/yuidoc/issues/198

The proposed solution is to specify an array of Foo objects as "Foo[]".  I've tried it in yuidoc 0.3.45 and 0.3.49, and yuidoc just ignores the "[]" part and only shows Foo as the type.

Example.  In my method comment, I have the following parameter annotation:
    @param entities {Object[]} blah blah blah

but the html output doc shows:
    * entities &lt;Object&gt;

**Comment by okuryu** [comment]
Closing in favor of https://github.com/yui/yuidoc/issues/198#issuecomment-141919621.
