### ISSUE TITLE
No output and do nothing when i use yuidoc

### ISSUE THREAD

**Issue by ThomasMoquet** [yui/yuidoc#245]
Hello everyone, 

I've installed yuidoc with "npm -g install yuidocjs" and have no error, but when I try to use it, it do nothing : 

	site@ubuntu:~/casperjs-sqlite3$ yuidoc .
	site@ubuntu:~/casperjs-sqlite3$ yuidoc -h
	site@ubuntu:~/casperjs-sqlite3$ 

I search but found nothing about it, any ideas ?

Thanks.

Thomas

**Comment by okuryu** [comment]
Closing, please let me know if you have still this issue.
