### ISSUE TITLE
Document stand-alone functions

### ISSUE THREAD

**Issue by Couto** [yui/yuidoc#25]
This is probably a simple question

Taking an AMD approach, how do you properly document a stand-alone function?
I've been looking at the docs and examples, but I wasn't able to find anything related…

Example to help clarify my problem:

``` javascript
/**
 * bind
 *
 * @version 0.0.1
 * @module function
 */
define(function () {

    /**
     * binds a function to a given object (context)
     *
     * @function
     * @param {Function} fn Function to be bound
     * @param {Object} context Object that will serve as context
     * @return {Function} bound function
     */
    return function (fn, context) { /* code */ }

});
```

This is an AMD module that returns a simple bind function, but because it's not a class and it's not exactly a constructor, i totally fail to make that function's documentation appear in the generated docs, at least correctly.

**Comment by barmalei** [comment]
+100

**Comment by raphapassini** [comment]
I'm facing the same issue right now. I would like to have an "official" solution!
+1

**Comment by okuryu** [comment]
Hi All,

You know @caridy have been very busy for other stuffs, so I'd love to work for this now.

Many people are trying to write JavaScript in ES6 (ES2015) modules now. I think making more affinity for modules is worth going, but I don't have concrete approach yet. If you have any feedback, please feel free to write to me.

**Comment by balupton** [comment]
Just ran into this here:
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fbevry%2Fassert-helpers%2Fblob%2Ff45d1b9f23629ed004c3afc76b501eef212dfffa%2Fesnext%2Flib%2Fhelpers.js&sa=D&sntz=1&usg=AFQjCNFXQhSr5cQ-XulJrxvDhbtYuWyj_Q

Documenting as a fictitious class as suggested [here](http://www.google.com/url?q=http%3A%2F%2Fstackoverflow.com%2Fq%2F12686569%2F130638&sa=D&sntz=1&usg=AFQjCNEPJREPr7ZQGYcssXqKxM2s-SdSpQ) didn't work for me:
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fbevry%2Fassert-helpers%2Fblob%2Fb9b7db5f22141f27895d8ae5a855b34eb0b23b19%2Fesnext%2Flib%2Fhelpers.js&sa=D&sntz=1&usg=AFQjCNHTOWvhV3uTnX9IOJR9l4PfdZgY2g

[Also have a discussion in the Google Group.](https://groups.google.com/forum/#!topic/yuidoc/sOf3aafbcnA)

**Comment by pflannery** [comment]
@balupton Your comments are parsed by YUIDoc but it sounds like the template your using doesn't render this scenario.

example:
```js
/**
Alias for setTimeout with paramaters reversed
@private
@etaeta global
@method wait
@param {Number} delay Delay to send to setTimeout
@param {Function} fn Function to send to setTimeout
@return {Object} result of the setTimeout call
*/
function wait() {
		
}
```

example output json snippet

```js
    "classitems": [
        {
            "file": "test.js",
            "line": 1,
            "description": "Alias for setTimeout with paramaters reversed",
            "access": "private",
            "tagname": "",
            "itemtype": "method",
            "name": "wait",
            "params": [
                {
                    "name": "delay",
                    "description": "Delay to send to setTimeout",
                    "type": "Number"
                },
                {
                    "name": "fn",
                    "description": "Function to send to setTimeout",
                    "type": "Function"
                }
            ],
            "return": {
                "description": "result of the setTimeout call",
                "type": "Object"
            },
            "class": ""
        }
    ]
```
It's also possible to add custom tags i.e. @blah test results in "blah": "test" in the meta data.

If the default template doesn't deal with this then maybe there is a custom template that can handle this scenario or via some custom attribute

**Comment by brianpeiris** [comment]
+1 Support for the revealing module pattern or ES6 in general would be great.

**Comment by Jaloko** [comment]
+1 for this feature. I'll have to use the class syntax for now.

**Comment by dsibiski** [comment]
+1

**Comment by jbaydar** [comment]
+1

**Comment by kyleolsondesign** [comment]
+1

**Comment by chopper** [comment]
+1

**Comment by talhaobject90** [comment]
+1

**Comment by talhaobject90** [comment]
+1

**Comment by chopper** [comment]
+1

**Comment by Ettapp** [comment]
+1

**Comment by mister-walter** [comment]
+1

**Comment by barmalei** [comment]
Actually I have applied an approach that helps me to solve module/package level methods definition. The following assumptions have to be taken in account:

- Don't use module at all, replace it with package. 
- Define a package as a class that is tagged with "package" access. For instance "commons.io" package can be defined with yuidoc as follow:
```
/**
 * <Package description>
 * @class commons.io
 * @access package
 */
- You can consider package as a module if you want and place methods and variables there as you do it for a normal JS class.

You can try zebkit yuidoc theme to see how the idea works:
https://github.com/barmalei/yuidoc-zebkit-theme

**Comment by leebenson** [comment]
Apologies for contributing to +1 spam, but is there any movement on this?

It was suggested 4 years ago, and 'coming' a year later. Now that ES6 has most definitely landed and large swaths of code do away with modules/classes altogether, a `@function` tag would be put to good use!

**Comment by davicitoafc** [comment]
+1

**Comment by Spongman** [comment]
5 1/2 years...

**Comment by ef4** [comment]
As far as I can tell this is already fixed.

I came upon this issue because I was wondering how to do this, but then I found other working examples, like:

```js
/**
  Shifts the coordinates of the given bounds using the provided
  x and y axis offset.

  @function shiftedBounds
  @param {Object} bounds The original bounds.
  @param {number} dx X axis offset.
  @param {number} dy Y axis offset.
  @return {Object} The newly calculated bounds.
*/
export function shiftedBounds(bounds, dx, dy) {
```
