### ISSUE TITLE
util.error: Use console.error instead

### ISSUE THREAD

**Issue by Bizarrus** [yui/yuidoc#325]
The error message `util.error: Use console.error instead` comes up each line

    util.error: Use console.error instead
    yuidoc: (warn): Setting default charset to binary
    util.error: Use console.error instead
    info: (yuidoc): Starting YUIDoc@0.6.0 using YUI@3.18.1 with NodeJS@0.12.0
    util.error: Use console.error instead
    info: (yuidoc): Starting YUIDoc with the following options:
    util.error: Use console.error instead
    info: (yuidoc):
    { outdir: 'Docs',
      linkNatives: 'true',
      extension: '.java',
      port: 3000,
      nocode: true,
      helpers: [ './Theme/helpers/helpers.js' ],
      themedir: './Theme/',
      configfile: './yuidoc.json',
      paths: [ '.\\\\Source\\\\' ],
      project:
       { name: 'Example API',
         description: '',
         version: '0.0.1',
         url: 'http://example.com/',
         logo: 'assets/img/logo.png' } }
    util.error: Use console.error instead
    info: (yuidoc): YUIDoc Starting from: .\\Source\\
    util.error: Use console.error instead
    warn: (yuidoc): Found out dir, deleting: Docs
    util.error: Use console.error instead
    info: (yuidoc): Making out dir: Docs
    util.error: Use console.error instead
    info: (yuidoc): Parsed 40 files in 0.06 seconds
    util.error: Use console.error instead
    info: (builder): Importing helpers: ./Theme/helpers/helpers.js
    util.error: Use console.error instead
    info: (builder): Building..
    util.error: Use console.error instead
    info: (builder): Compiling Templates
    util.error: Use console.error instead
    info: (builder): Making default directories: classes,modules,files
    util.error: Use console.error instead
    info: (builder): Copying Assets
    util.error: Use console.error instead
    info: (builder): Rendering and writing 0 modules pages.
    util.error: Use console.error instead
    info: (builder): Finished writing module files
    util.error: Use console.error instead
    info: (builder): Rendering and writing 37 class pages.
    util.error: Use console.error instead
    info: (builder): Loading theme from Theme\theme.json
    util.error: Use console.error instead
    info: (builder): Preparing index.html
    util.error: Use console.error instead
    info: (builder): Writing API Meta Data
    util.error: Use console.error instead
    info: (builder): Writing index.html
    util.error: Use console.error instead
    info: (builder): Finished writing class files
    util.error: Use console.error instead
    info: (builder): Finished writing 38 files in 0.86 seconds
    util.error: Use console.error instead
    info: (yuidoc): Completed in 0.95 seconds

**Comment by okuryu** [comment]
Yeah, it's occurs on Node.js v0.12 and io.js. I'll take a look.

**Comment by Bizarrus** [comment]
Thanks :)
I had try to find it out to fix it locally but i dont find any `utils.log` in the files.

**Comment by okuryu** [comment]
Yes. Actually, YUI uses `util.error` (not YUIDoc). I'll try to remove YUI's functions or change it to something.

**Comment by okuryu** [comment]
Published `yuidocjs@0.7.0`.
