### ISSUE TITLE
yuidoc . runs node instead of nodejs on ubuntu 14.04

### ISSUE THREAD

**Issue by eagles051387** [yui/yuidoc#342]
Hi guys on ubuntu 14.04 when runnign yuidoc . it tries to invoke the document generation using node which doesnt exist on 14.04. there it is caleld nodejs and is foudn under /usr/bin/nodejs

can this be fixed where such a work around is nto required.

ln -s /usr/bin/nodejs /usr/bin/node solves the issue tryign to invoke node which does not exist.

**Comment by uxmaster** [comment]
I don't know a single project compatible with this Debian/Ubuntu specific alternative name, so if you don't want to be an outsider, install `nodejs-legacy` package.

**Comment by eagles051387** [comment]
what does nodejs-legacy offer that a normal install does not?

On Fri, Apr 10, 2015 at 3:16 PM, uxmaster <notifications@github.com> wrote:

> I don't know a single project compatible with this Debian/Ubuntu specific
> alternative name, so if you don't want to be an outsider, install
> nodejs-legacy package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yui/yuidoc/issues/342#issuecomment-91553992>.
>



-- 
Jonathan Aquilina

**Comment by okuryu** [comment]
Yes, please install `nodejs-legacy`.
http://stackoverflow.com/a/21171188/1242853

**Comment by uxmaster** [comment]
`nodejs-legacy` offers few symlinks:
```
/usr/bin/node -> nodejs
/usr/share/man/man1/node.1.gz -> nodejs.1.gz
```
and it's in conflict with `node` package (Amateur Packet Radio Node program).
