### ISSUE TITLE
Add fenced code block syntax highlighting via highlight.js

### ISSUE THREAD

**Issue by jnfingerle** [yui/yuidoc#358]
Syntax highlighting for fenced code blocks is broken, presumably since the switch to markdown-it. They describe in their README how to enable it via highlight.js. It would be great if this could be enabled.

**Comment by okuryu** [comment]
Hmm, I'll take a look asap.

**Comment by okuryu** [comment]
@jnfingerle I'm not able to reproduce this problem. Could you provide a repro example?

**Comment by jnfingerle** [comment]
The following ...
```
/**
 * TEST
 * @module test1
 */
/**
 * ```handlebars
 * {{#hilfe-anzeige}}
 *   <h1>Ein Text mit Hilfe{{hilfe-anker}}</h1>
 *   {{#hilfe-text}}
 *     <p>
 *       Eine Erklärung
 *     </p>
 *   {{/hilfe-text}}
 * {{/hilfe-anzeige}}
 * ```
 *
 *
 * ```
 * {{#hilfe-anzeige as |help|}}
 *   <h1>Ein Text mit Hilfe{{hilfe-anker ref=help}}</h1>
 *   {{#hilfe-text ref=help}}
 *     <p>
 *       Eine Erklärung
 *     </p>
 *   {{/hilfe-text}}
 * {{/hilfe-anzeige}}
 * ```
 *
 * @class test2
 */
```

... leads to pretty weird highlighting at my end. And 

```
/**
 * TEST
 * @module test1
 */
/**
 * ```handlebars
 * {{#hilfe-anzeige}}
 *   <h1>Ein Text mit Hilfe{{hilfe-anker}}</h1>
 *   {{#hilfe-text}}
 *     <p>
 *       Eine Erklärung
 *     </p>
 *   {{/hilfe-text}}
 * {{/hilfe-anzeige}}
 * ```
 *
 *
 *
 * @class test2
 */
```
seems not to render anything at all.

HTH

**Comment by okuryu** [comment]
Are you trying to use the markdown-it's highlight option? If so, I think that it doesn't works for now because yuidoc.json isn't able to accept a highlighter function.

YUIDoc currently uses the code prettifier, but it's old version. I think there is room for improvement.

**Comment by jnfingerle** [comment]
Oh, sorry. Seems to have been some weird behaviour of a custom theme.
