### ISSUE TITLE
@param {Object[]}  not recognized

### ISSUE THREAD

**Issue by jnfingerle** [yui/yuidoc#368]
Using 0.8.0 and the default theme 

    @param {Object[]}

will be rendered as "Object" while

    @param {Foo[]}

will be rendered as "Foo[]".

From my point of view, the second behaviour should be the expected behaviour for the first one as well.

**Comment by okuryu** [comment]
They look same behavior to me.

```
/**
 * @class MyClass
 */

/**
 * @param p1 {Object[]} a parameter 1
 * @param p2 {Foo[]} a parameter 2
 * @method method1
 */
```

![2015-08-03 at 23 32](https://cloud.githubusercontent.com/assets/34588/9039683/06b488e0-3a38-11e5-8807-30db2f7b64d4.png)

**Comment by BlueRaja** [comment]
Seems like a regression of #198 and #229

**Comment by okuryu** [comment]
@BlueRaja Okay, let me try to investigate this in the next week.

**Comment by okuryu** [comment]
Closing in favor of https://github.com/yui/yuidoc/issues/198#issuecomment-141919621.
