### ISSUE TITLE
Add @rest tag for documenting REST endpoints

### ISSUE THREAD

**Issue by JDillon522** [yui/yuidoc#400]
I'm adding documentation to my team's backend express API and I'm trying to find a reasonable way to document all the different REST endpoints. For example, how would I properly document `POST /api/billing/card`? 

As it stands I'm thinking of just making a class called "REST Endpoints", but it would be really great if there was an easy built-in way to do this.

**Comment by dangreenisrael** [comment]
+1 for this.

@JDillon522 What did you have in mind?
@stefanpenner I'd be willing to work on a PR if a maintainer could point me in the right direction

**Comment by JDillon522** [comment]
Its been a long time since I really gave this any thought, but probably a tag on the same level as `@class` or `@method` that when generated register all the api endpoints in a readable fashion. Possibly something like an `@schema` tag to cover the necessary format for the data in a body. An `@headers` tag would be useful if there were something specific to denote, like authorization.

**Comment by dangreenisrael** [comment]
I'm imaging something like
```
@Endpoint /api/something
@POST
@body 
{
  foo:"bar"
} 
@returns 
{
  id: 1,
  foo:"bar"
}
```


```
@Endpoint /api/something
@GET 
@returns 
{
  id: 1,
  foo:"bar"
}
```
