### ISSUE TITLE
wrong rendering of markdown code blocks 

### ISSUE THREAD

**Issue by EyMaddis** [yui/yuidoc#421]
Hi,
using the following documentation:

```js
import Ember from 'ember';

/**
 * Displays tuples are a table, one row with the key and one with the corresponding values
 *
 * @class KeyValueTableComponent
 * @extends Ember.Component
 */
export default Ember.Component.extend({
    /**
     * A list of tuples. It is a list to keep the order.
     * The tuple list is structured like the following example:
     * ```
     * [
     *   {key: "myProperty", value: "myValue"}
     * ]
     * ```
     *
     * @property tuples
     * @type {Array}
     * @required
     */
    tuples: null
});

```

will render as the following:
![image](https://cloud.githubusercontent.com/assets/1409100/17173494/7a4b869a-53fb-11e6-977c-18b7f73daee0.png)

Another issue is that without the beginning new line, the rendering will also be invalid:
```js
     * ```[
     *   {key: "myProperty", value: "myValue"}
     * ]```
```
will render to:
![image](https://cloud.githubusercontent.com/assets/1409100/17173561/cea01d78-53fb-11e6-9384-9fe48a7024bc.png)

Right now I am forced to use inline code.

**Comment by schnittstabil** [comment]
@EyMaddis I can't confirm that, it works like expected (YUIDoc@0.10.2 using YUI@3.18.1 with NodeJS@4.4.7).

However, to be honest, I've had the same issue a while ago which had been caused by my customized, but outdated theme…

**Comment by EyMaddis** [comment]
Ok, I disabled the custom layout and this fixes the weird indentation, but the new line issue still exists

**Comment by schnittstabil** [comment]
@EyMaddis Unfortunately, your're out of luck, `yuidoc` uses the [CommonMark syntax](http://spec.commonmark.org/0.26/#example-110), which supports:

```
```[
```

However, CommonMark expects `[` to be a language identifier (e.g. `js` or `ruby`), thus it is rendered as `<pre><code class="language-[">…`.

**Comment by EyMaddis** [comment]
@schnittstabil hm, then I would have guessed that ` '''js [` would work, but it doesn't, too bad.

**Comment by schnittstabil** [comment]
From the [docs](http://spec.commonmark.org/0.26/#info-string):

> **The line** with the opening code fence may optionally contain some text following the code fence; this is trimmed of leading and trailing spaces and called the *info string*. …

**Comment by EyMaddis** [comment]
Ok, then this can get closed. Everything else is due to using a custom theme.

Thanks for the support!
