### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array

### ISSUE THREAD

**Issue by l1x** [yui/yuidoc#453]
While building nomad ui:

```
> nomad-ui@0.0.0 build
> ember build --environment=production

WARNING: Node v15.12.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
Environment: production
⠸ building... [Babel: ember-cli-test-loader > applyPatches]error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:716:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/home/l1x/go/src/github.com/hashicorp/nomad/ui/node_modules/ember-cli-test-loader/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/home/l1x/go/src/github.com/hashicorp/nomad/ui/node_modules/ember-cli-test-loader/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:369:20)
    at ChildProcess.emit (node:domain:470:12)
    at emit (node:internal/child_process:920:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
error: --------------------------------------------------------------------------
error: Node.js version: v15.12.0
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.2
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```

**Comment by zaferhuzmeli** [comment]
Hi, did you solve it?

**Comment by l1x** [comment]
> Hi, did you solve it?

Yes, by downgrading NodeJS.

**Comment by lskillington** [comment]
@l1x which Node version did you downgrade to?

**Comment by l1x** [comment]
> @l1x which Node version did you downgrade to?

Great question, can't remember and already moved away from this. You can try 1 major version downgrade and keep going until it works. Sorry I could not be more useful.

**Comment by lskillington** [comment]
All good, got it working! For anyone else coming across this, I moved down to 14.15.1

**Comment by Techn1x** [comment]
broken on 16.13.0 too, which is an active node LTS. downgrading doesn't seem like a valid long term solution here

**Comment by l1x** [comment]
> broken on 16.13.0 too, which is an active node LTS. downgrading doesn't seem like a valid long term solution here

Welcome to nodejs. Please enjoy the ride.

**Comment by sjonkeesse** [comment]
```
npm install -g n
sudo n 14.15
```

**Comment by omnivagant** [comment]
Noticed this when trying to upgrade for our Alpinelinux Nomad users.

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/28610

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/28611

**Comment by Krishna1705** [comment]
> ```
> npm install -g n
> sudo n 14.15
> ```

this node version works for me... i also downgraded to this node version 14.15.5 to resolve the same issue

**Comment by langalex** [comment]
Can this be re-opened? Downgrading Node is not a fix.

**Comment by cah-brian-gantzler** [comment]
Was working fine on Node 20.3.0 and appeared to be working fine. Go to run my tests today and am now getting this error. Dont know what changed to cause it. 

Jumping between projects and forgot this one was pnpm. It does not work when I install with npm, but does work when I install with pnpm on node 20. Not sure where the breakdown is.
