### ISSUE TITLE
yuidoc.json ignorePaths option does not work

### ISSUE THREAD

**Issue by guozheng** [yui/yuidoc#5]
It seems like there is a bug in validatePaths function in lib/util.js:

if (ignore) {
        if (!(ignore instanceof Array)) {
            ignore = [ignore];
        }
        var p = [];
        paths.forEach(function(v) {
            ignore.forEach(function(i) {
                if (v.indexOf(i) === -1) {
                    p.push(v);
                }
            });
        });
        paths = p;
    }

So, if ignore array contains at least two paths, for example:
paths = ['a', 'b', 'c']
ignore = ['a', 'b']
When you use the two forEach to check each element in paths, say, you check 'a' from paths against 'a', 'b' in ignore, since 'a'.indexOf('b') will give you -1, 'a' will be added to the final paths array instead of getting filters.

Instead, should do something like this:

if (ignore) {
        if (!(ignore instanceof Array)) {
            ignore = [ignore];
        }
        var p = [];
        var shouldIgnore = false;
        paths.forEach(function(v) {
            shouldIgnore = false;
            ignore.forEach(function(i) {
                if (!shouldIgnore && v.indexOf(i) !== -1) {
                    shouldIgnore = true;
                }
            });
            if (!shouldIgnore) {
                p.push(v);
            }
        });
        paths = p;
}

**Comment by przmak** [comment]
{
"options": {
    "ignorePaths": [
      "./app/vendor/",
    ],
    "paths": [
      "./app/",
    ],
 }
}

**Comment by okuryu** [comment]
@przmak Try `exclude` option to remove directory.

**Comment by gokulk13** [comment]
that works for me @okuryu
