### ISSUE TITLE
Problems navigating from index to any method or property

### ISSUE THREAD

**Issue by drkarl** [yui/yuidoc#89]
When on the index tab of a class, you click on a method or property listed on that index, all you can see is a blank page. The url changes has #method_name appended, and if you click enter on the url bar it works, so the problem must be a javascript error.

If you try it without debugging there are no javascript errors, but debugging step by step there are javascript errors.

I get to a point on apidocs.js line 205, in pjax.updateTabState function, which has an inner  function called scrollToNode, which has a setTimeOut calling an anonymous function, there's the following error:

Uncaught TypeError: Cannot read property 'responseText' of null

It happens twice, and it points to combo:56

Uncaught TypeError: Cannot read property 'responseText' of null combo:56
n._onPjaxIOComplete combo:56
e.Subscriber._notify combo:14
e.Subscriber.notify combo:14
e.CustomEvent._notify combo:14
e.CustomEvent._procSubs combo:14
e.CustomEvent.fireSimple combo:14
e.CustomEvent.fire combo:14
E.fire combo:14
o._evt combo:49
o.complete combo:49
o._rS combo:49

If I click to the link combo:56 it takes me to this piece of code

/*
YUI 3.7.0 (build 5625)
Copyright 2012 Yahoo! Inc. All rights reserved.
Licensed under the BSD License.
http://yuilibrary.com/license/
_/
YUI.add("pjax-content",function(e,t){function n(){}n.prototype={getContent:function(t){var n={},r=this.get("contentSelector"),i=e.Node.create(t||""),s=this.get("titleSelector"),o;return r?n.node=i.all(r).toFrag():n.node=i,s&&(o=i.one(s),o&&(n.title=o.get("text"))),n},loadContent:function(t,n,r){var i=t.url;this._request&&this._request.abort(),this.get("addPjaxParam")&&(i=i.replace(/([^#]_)(#.*)?$/,function(e,t,n){return t+=(t.indexOf("?")>-1?"&":"?")+"pjax=1",t+(n||"")})),this._request=e.io(i,{arguments:{route:{req:t,res:n,next:r},url:i},context:this,headers:{"X-PJAX":"true"},timeout:this.get("timeout"),on:{complete:this._onPjaxIOComplete,end:this._onPjaxIOEnd}})},_onPjaxIOComplete:function(e,t,n){var r=this.getContent(t.responseText),i=n.route,s=i.req,o=i.res;s.ioURL=n.url,o.content=r,o.ioResponse=t,i.next()},_onPjaxIOEnd:function(){this._request=null}},n.ATTRS={addPjaxParam:{value:!0},contentSelector:{value:null},titleSelector:{value:"title"},timeout:{value:3e4}},e.PjaxContent=n},"3.7.0",{requires:["io-base","node-base","router"]});

I think this might be related to issue 88 

https://github.com/yui/yuidoc/issues/88

**Comment by metropt** [comment]
I tried yuidoc today and I got this problem.

Version number: `info: Starting YUIDoc@0.10.2 using YUI@3.18.1 with NodeJS@8.11.2`

Thank you

**Comment by timo-lindemann-victors** [comment]
We use yuidoc (in fact have for years) and this problem started to become apparent today. I can distinctly remember being able to use yuidoc from the file system without problems, but now I got this pjax error:

```
Uncaught TypeError: Cannot read property 'getById' of null
    at n.pjax.updateTabState (apidocs.js:234)
```

This happens in response to `cross-origin requests which are not supported for protocol schemes http, data, chrome, chrome-extension, https`.

## So, it actually seems to be the Same Origin Policy preventing ajax/pjax requests to the file system.

Is it possible to disable pjax completely when dealing with file:// urls?

* Versions: Node.js version: v6.10.3
* YUI version: 3.18.1
* YUIDoc version: 0.10.2
* This is part of ember-cli-yuidoc, which in turn is part of our application.

**Comment by timo-lindemann-victors** [comment]
Upon further investigation: there *is* code to disable pjax for file system accesses [here](https://github.com/yui/yuidoc/commit/839b9d65f81537f257ed828308de1836db1f6326#diff-4f9309047666455f7f02cf4b3db11f28R16); the commit is already quite old.

I also tried with master this morning, as 0.10.3 seems to have not been released yet; same problems.

I have not yet discovered why it doesn't work (anymore?). I am quite sure it *did* work until recently.

**Comment by timo-lindemann-victors** [comment]
I moved my two previous posts to a new issue that has not been closed for years.
