### ISSUE TITLE
Can't generate doc if line endings of source file was Mac/CR

### ISSUE THREAD

**Issue by qiluo** [yui/yuidoc#96]
First got "warn: (docparser): Missing item type:  common\test.js:1", then there was no module/classes found.

Just fixed it by changing line endings from Mac to Unix.

A file with Mac line endings will reproduce this bug.

Here's discussion,
https://groups.google.com/forum/#!topic/yuidoc/_PNflxx4V7s

**Comment by okuryu** [comment]
#308 is ready for reviews.
